// THIS FILE IS GENERATED BY cppust-gen, YOU CAN CHANGE THIS FILE ON YOUR OWN

#pragma once

#include <cppust/cppust.hpp>

#include <iostream>

namespace nmea {

class DecoderStatus {
#include "decoder_status.inc.hpp"

public:
    // WRITE YOUR OWN CODE HERE
};

}

#include "decoder_status.fmt.hpp"
